import { DATA_SOURCE_LABELS } from "./chatbotApi";
export function buildChatbotPrompt({ message, history = [], appData = {}, contextEngine, usedSources = [] }) {
  const conversation = history
    .map((turn) => `${turn.role === "user" ? "Owner" : "Assistant"}: ${turn.content}`)
    .join("\n");

  const dataSections = usedSources.length
    ? usedSources
        .map((key) => `${DATA_SOURCE_LABELS[key] ?? key}:\n${JSON.stringify(appData[key], null, 2)}`)
        .join("\n\n")
    : "(Tidak ada data tambahan yang diambil untuk pertanyaan ini.)";

  return `
You are an AI assistant for a coffee shop's internal admin dashboard.
You help the shop owner/staff understand their inventory, menu, plans,
sales, and the AI-generated business insight below.

DATA RETRIEVED FOR THIS QUESTION:
${dataSections}

Latest ML sales predictions for the active plan:
${JSON.stringify(contextEngine?.predictions ?? [], null, 2)}

Weather forecast for the active plan period:
${JSON.stringify(contextEngine?.weather ?? {}, null, 2)}

Upcoming holidays within the active plan period:
${JSON.stringify(contextEngine?.holidays ?? [], null, 2)}

Latest AI business insight (generated by the context engine from the 3 data above):
${JSON.stringify(contextEngine?.insight ?? { recommendations: [] }, null, 2)}

RULES:
- Only answer using the data provided above. Do not invent numbers, dates, or items.
- If the data provided doesn't contain the answer, say so plainly instead of guessing.
- If no data was retrieved and the question actually needs shop data, say you don't have that information right now instead of making it up.
- Keep answers concise and practical — this is for a busy shop owner, not a report.
- Do not use overly formal or robotic language.

${conversation ? `CONVERSATION SO FAR:\n${conversation}\n` : ""}
Owner: ${message}
Assistant:
`.trim();
}
