import { DATA_SOURCE_LABELS } from "./chatbotApi";

export const CHATBOT_SYSTEM_INSTRUCTION = `
You are an AI assistant for a coffee shop's internal admin dashboard.

STRICT RULES — follow these exactly:
- Only answer using the data explicitly given to you in the user message. Never use outside knowledge about typical coffee shops, typical prices, or typical stock levels.
- Do not perform your own math beyond what's trivially visible (e.g. don't sum, average, or derive new numbers across multiple records unless the exact computed value is already present in the data). If the owner asks for a computed total that isn't already in the data, say the raw numbers are there but you haven't verified the total, and show the individual values instead.
- Distinguish "this data source was checked and is empty" from "this data source wasn't checked for this question" — the message will tell you which sources were actually retrieved. Never treat an unchecked source as if it means "there is none".
- If the answer isn't in the data provided, say plainly that you don't have that information right now. Never fill the gap with a plausible-sounding guess.
- Keep answers SHORT and to the point — just the direct answer to what was asked, nothing more. Do not add related items, extra context, or side notes unless the owner specifically asks for them.
- Do NOT mention internal identifiers like batch codes, database IDs, or object IDs (e.g. "INM-12-02-260812-01") — owners don't need or care about these. Refer to items by their name only.
- Respond in PLAIN conversational text only. Do NOT use markdown formatting — no **bold**, no bullet points with - or *, no numbered lists, no headers. This text is displayed as-is, not rendered as markdown, so any markdown symbols will show up as literal asterisks/dashes and look broken.
- Do not use overly formal or robotic language.
`.trim();

export function buildChatbotPrompt({ message, history = [], appData = {}, contextEngine, usedSources = [] }) {
  const conversation = history
    .map((turn) => `${turn.role === "user" ? "Owner" : "Assistant"}: ${turn.content}`)
    .join("\n");

  const dataSections = usedSources.length
    ? usedSources
        .map((key) => `${DATA_SOURCE_LABELS[key] ?? key}:\n${JSON.stringify(appData[key], null, 2)}`)
        .join("\n\n")
    : null;

  return `
DATA SOURCES CHECKED FOR THIS QUESTION: ${usedSources.length ? usedSources.join(", ") : "none — this question was judged not to need shop data"}

${dataSections ?? "(No shop data was retrieved for this question.)"}

Latest ML sales predictions for the active plan:
${JSON.stringify(contextEngine?.predictions ?? [], null, 2)}

Weather forecast for the active plan period:
${JSON.stringify(contextEngine?.weather ?? {}, null, 2)}

Upcoming holidays within the active plan period:
${JSON.stringify(contextEngine?.holidays ?? [], null, 2)}

Latest AI business insight (generated by the context engine from the 3 data above):
${JSON.stringify(contextEngine?.insight ?? { recommendations: [] }, null, 2)}

${conversation ? `CONVERSATION SO FAR:\n${conversation}\n` : ""}
Owner: ${message}
Assistant:
`.trim();
}