export function buildContextPrompt(predictions, weather, holidays = []) {
  const context = {
    predicted_next_week_sales: predictions,
    weather_forecast: weather,
    upcoming_holidays: holidays,
  };

  return `
You are an AI business assistant for a coffee shop.

Analyze the sales predictions together with weather and upcoming holidays
to provide the MOST IMPORTANT business insights for the plan period ahead.

The predicted sales are already generated by a forecasting model.
DO NOT change, recalculate, increase, decrease, or replace any prediction.
Use the prediction values exactly as provided.

Available data:
${JSON.stringify(context, null, 2)}

Focus on:
- How weather may affect the predicted demand.
- How upcoming holidays may affect customer traffic or demand.
- Important opportunities or risks related to the predictions.
- Practical actions the cafe owner should consider.

IMPORTANT:
- Do not create new predictions.
- Do not modify the existing prediction numbers.
- If upcoming_holidays is empty, do not mention holidays.
- Only use information supported by the provided data.
- Do not list every predicted menu.
- Mention a menu only when relevant to the insight.
- Include prediction numbers when useful.
- Keep each recommendation natural, concise, and around 1-2 sentences.
- Do not use overly formal or robotic language.
- Do not invent numbers, percentages, quantities, dates, or relationships.
- If weather_forecast includes a "coverage_note", it means weather data doesn't cover the full plan period. For days beyond that coverage, don't mention or imply anything about weather — instead, base any recommendation for those days purely on predicted sales and/or holidays if relevant. Never treat missing weather data as "clear/calm weather".
- Return exactly 3 recommendations, ranked from most important to least important.

PRIORITY:
Rank recommendations from MOST IMPORTANT to LEAST IMPORTANT.

Prioritize in this order:
1. Upcoming holidays, because they are rare opportunities that may affect
   customer traffic and create opportunities to increase sales.
2. Significant weather conditions that may affect demand.
3. Important insights from the predicted sales.

If a relevant upcoming holiday exists, prioritize it as the first recommendation.
Do not mention a holiday if it does not provide a meaningful business opportunity.

Return ONLY valid JSON:

{
  "recommendations": [
    "Temperatures are expected to reach 34C next week. Increase preparation of iced beverages to support the predicted demand.",
    "August 17 is a national holiday. Prepare additional stock for potentially higher customer traffic.",
    "Cappuccino is forecasted to be a strong seller at 20 units. Make sure enough milk and beans are stocked to keep up."
  ]
}
`.trim();
}
